### ISSUE TITLE
Allow for users to omit certain data values from packet captures

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/capture-packets#1]
Currently sensitive information is likely to be captured in the packets. Usually the exact values of this data isn't relevant to debugging a networking problem, instead it's the presence or absence of the data. It'd be good to provide a way for users to "clean" the packet capture of the secret values without compromising on being able to load them into Wireshark.

**Comment by sethmlarson** [comment]
Resource for how to decrypt TLS packets manually:
https://lowleveldesign.org/2016/03/09/manually-decrypting-https-request/

Using scapy might be a good idea here: https://scapy.net/

**Comment by sethmlarson** [comment]
Some things that may need to be scrubbed:

- IP addresses
- Domain names in DNS
- Hosts in HTTP
- Hosts in SNI
- Hosts in certificates
- Authorization HTTP header

**Comment by AshvinGudaliya** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @bodd1593, @esneko, @lovelly, @angristan, @taco-c, @cartime99, @liyh12, @Ksuksu3, @tongcan, @geanyinabottle69, @DanteLorenzo, @lpsm-dev, @fbraz3, @samsheff, @THtianhao, @seekaddo, @nj-steve, @BlackJack0, @DrPep, @hugmatj
